export const navMenu = [
  { key: "home", path: "/" },
  { key: "news", path: "news" },
  { key: "market", path: "market" },
  { key: "masters", path: "masters" },
  { key: "profile", path: "profile" },
];

// export const BASE_URL =
//   "https://ukrainians-in-the-netherlands-backend.onrender.com/api";
export const BASE_URL = "http://localhost:3030/api";

export const masters = [
  {
    id: 1,
    name: "Марія К.",
    specialty: "Кондитер",
    imageUrl: "",
    education: "Закінчила кулінарну академію у Львові",
    description: "5 років досвіду у виготовленні тортів та десертів",
    rating: 4.8,
    languages: ["Українська", "Англійська"],
    email: "maria.bakery@example.com",
    phone: "+31612345678",
    instagram: "@maria_cakes",
    telegram: "maria_cakes_nl",
    whatsapp: "+31612345678",
    portfolio: ["/img1.jpg", "/img2.jpg", "/img3.jpg"],
    minOrder: "від €50",
    location: {
      address: "Amsterdam, NL",
      lat: 52.3676,
      lng: 4.9041,
    },
    author: 1,
  },
  {
    id: 2,
    name: "Олександр П.",
    specialty: "Фотограф",
    imageUrl: "",
    education: "Закінчила кулінарну академію у Львові",
    description: "5 років досвіду у виготовленні тортів та десертів",
    rating: 4.8,
    languages: ["Українська", "Англійська"],
    email: "maria.bakery@example.com",
    phone: "+31612345678",
    instagram: "@maria_cakes",
    telegram: "maria_cakes_nl",
    whatsapp: "+31612345678",
    portfolio: ["/img1.jpg", "/img2.jpg", "/img3.jpg"],
    minOrder: "від €50",
    location: {
      address: "Amsterdam, NL",
      lat: 52.3676,
      lng: 4.9041,
    },
    author: 2,
  },
  {
    id: 3,
    name: "Ірина С.",
    specialty: "Майстер манікюру",
    imageUrl: "",
    education: "Закінчила кулінарну академію у Львові",
    description: "5 років досвіду у виготовленні тортів та десертів",
    rating: 4.8,
    languages: ["Українська", "Англійська"],
    email: "maria.bakery@example.com",
    phone: "+31612345678",
    instagram: "@maria_cakes",
    telegram: "maria_cakes_nl",
    whatsapp: "+31612345678",
    portfolio: ["/img1.jpg", "/img2.jpg", "/img3.jpg"],
    minOrder: "від €50",
    location: {
      address: "Amsterdam, NL",
      lat: 52.3676,
      lng: 4.9041,
    },
    author: 3,
  },
  {
    id: 4,
    name: "Тарас Г.",
    specialty: "Кераміст",
    imageUrl: "",
    education: "Закінчила кулінарну академію у Львові",
    description: "5 років досвіду у виготовленні тортів та десертів",
    rating: 4.8,
    languages: ["Українська", "Англійська"],
    email: "maria.bakery@example.com",
    phone: "+31612345678",
    instagram: "@maria_cakes",
    telegram: "maria_cakes_nl",
    whatsapp: "+31612345678",
    portfolio: ["/img1.jpg", "/img2.jpg", "/img3.jpg"],
    minOrder: "від €50",
    location: {
      address: "Amsterdam, NL",
      lat: 52.3676,
      lng: 4.9041,
    },
    author: 4,
  },
  {
    id: 5,
    name: "Олена В.",
    specialty: "Майстриня",
    imageUrl: "",
    education: "Закінчила кулінарну академію у Львові",
    description: "5 років досвіду у виготовленні тортів та десертів",
    rating: 4.8,
    languages: ["Українська", "Англійська"],
    email: "maria.bakery@example.com",
    phone: "+31612345678",
    instagram: "@maria_cakes",
    telegram: "maria_cakes_nl",
    whatsapp: "+31612345678",
    portfolio: ["/img1.jpg", "/img2.jpg", "/img3.jpg"],
    minOrder: "від €50",
    location: {
      address: "Amsterdam, NL",
      lat: 52.3676,
      lng: 4.9041,
    },
    author: 5,
  },
  {
    id: 6,
    name: "Віктор Л.",
    specialty: "Програміст",
    imageUrl: "",
    education: "Закінчила кулінарну академію у Львові",
    description: "5 років досвіду у виготовленні тортів та десертів",
    rating: 4.8,
    languages: ["Українська", "Англійська"],
    email: "maria.bakery@example.com",
    phone: "+31612345678",
    instagram: "@maria_cakes",
    telegram: "maria_cakes_nl",
    whatsapp: "+31612345678",
    portfolio: ["/img1.jpg", "/img2.jpg", "/img3.jpg"],
    minOrder: "від €50",
    location: {
      address: "Amsterdam, NL",
      lat: 52.3676,
      lng: 4.9041,
    },
    author: 6,
  },
  {
    id: 7,
    name: "Анна Д.",
    specialty: "Перекладач",
    imageUrl: "",
    education: "Закінчила кулінарну академію у Львові",
    description: "5 років досвіду у виготовленні тортів та десертів",
    rating: 4.8,
    languages: ["Українська", "Англійська"],
    email: "maria.bakery@example.com",
    phone: "+31612345678",
    instagram: "@maria_cakes",
    telegram: "maria_cakes_nl",
    whatsapp: "+31612345678",
    portfolio: ["/img1.jpg", "/img2.jpg", "/img3.jpg"],
    minOrder: "від €50",
    location: {
      address: "Amsterdam, NL",
      lat: 52.3676,
      lng: 4.9041,
    },
    author: 7,
  },
];
